### ISSUE TITLE
Kong Cookbook with AWS opsworks

### ISSUE THREAD

**Issue by hims10** [zuazo/kong-cookbook#1]
Hi there, 

I am trying to setup Kong within OpsWorks/Chef setup . I tried using the Kong cookbook https://github.com/zuazo/kong-cookbook getting an error "Could not read /opt/aws/opsworks/current/merged-cookbooks/kong into a Chef object: Option default must be a kind of [String, Array, Hash]! You passed 300." . This works fine on my desktop using kitchen . My guess this has to do with Chef versions = AWS opsworks restricts using Chef 11.10 and this cookbook may have been sanity-proofed for some other version. 

Let me know if you have any ideas around this  easy ways to circumvent. 

-Himanshu

**Comment by zuazo** [comment]
Some dependencies like the [`ssl_certificate`](https://supermarket.chef.io/cookbooks/ssl_certificate) cookbook require at least Chef `11.14.2`. I think Chef `11.10` it is too old. It's an a year and a half old.

I have been trying to test this cookbook using your Chef version with test-kitchen without success, sorry. You can try changing [the attribute default value](https://github.com/zuazo/kong-cookbook/blob/6f0d16265cd77a0d1cd243253083539a41335f8f/metadata.rb#L98) in the metadata to be a string. But it might not be enough to make it work.

**Comment by zuazo** [comment]
I do not think it makes much sense to continue supporting such old versions. I'm going to close this issue.

Please, feel free to respond if you disagree and I will reopen the issue.
