### ISSUE TITLE
install net-tools package instead of netstat cookbook dependency

### ISSUE THREAD

**Issue by vkhatri** [zuazo/kong-cookbook#8]
Cookbook could add a package resource `net-tools` instead of adding `netstat` cookbook dependency.

**Comment by zuazo** [comment]
Hi @vkhatri,

I don't know what you mean. `netstat` cookbook does just that: install `net-tools` package.

If you have encountered any problem with `netstat` cookbook, please, try to explain what your problem is.

**Comment by vkhatri** [comment]
@zuazo There is no problem with the cookbook. IMHO, it would be simpler to add the package `net-tools` in comparison to the `netstat` cookbook dependency (which only install a single package).

**Comment by zuazo** [comment]
@vkhatri I'm OK with including `netstat` cookbook. Previously I was using it only for testing with Docker, but I did not think it is was a bad idea to put it as a core dependency in this cookbook. The package name is not very obvious and may be different on other systems. Adding it a as a dependency or adding a package resource, I do not really think there is much difference.

Anyway, thanks for the proposal. Feel free to continue discussing it here if you disagree or if you encounter any problems with it.
